{% set name = "omero-server" %}
{% set version = "5.6.1" %}
{% set omero_build = "225" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

source:
  url: https://downloads.openmicroscopy.org/omero/{{ version }}/artifacts/OMERO.server-{{ version }}-ice36-b{{ omero_build }}.zip
  sha1: a3d85d2fa67e2e6478666e82affdc067092aa7c1
build:
  noarch: generic
  number: 0
  script_env:
    - VERSION_SUFFIX

requirements:
  run:
    - omero-dropbox =5.6
    - omero-py =5.6
    - openjdk >=8
    # postgresql=10 is linked against an older openssl which conflicts with other packages
    - postgresql =11
    - pytables
    - python =3
    - pyyaml
    - zeroc-ice36 =3.6.5

test:
  commands:
    - omero-server version
    - omero-server config get
    - omero-server admin rewrite
    # - omero-server admin diagnostics

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 (GPLv2)
  license_family: GPL2
  summary: OMERO server
  description: |
    From the microscope to publication, OMERO handles all your images in a secure central repository.
  doc_url: https://docs.openmicroscopy.org/omero/latest/sysadmins/index.html
  dev_url: https://github.com/ome/openmicroscopy

extra:
  recipe-maintainers:
    - ome
